### PR TITLE
Trying to solve flaky/failing E2E testing

### PR DESCRIPTION
**Pull request by adi-mohan**
#704  Trying with a set of changes pointed out in #632

### CODE REVIEW

**Comment by amaurymartiny** [comment]
Thanks for taking a look @adi-mohan! I'll merge if the `pr / test-e2e (pull_request)` action is green, feel free to push and experiment stuff on this PR.

**Comment by adi-mohan** [comment]
Okay. Just wanted to know about "Location is denied" error. Is it something that is faced commonly in the e2e tests(which we are trying to fix here)? The test-e2e check has failed due to this and my commit doesn't have change related to location. Is this the flaky behavior the issue concerns with?

**Comment by amaurymartiny** [comment]
The e2e test is:
- load the app
- deny location
- check that the "location is denied" error message is present.

It used to work (see commits before September https://github.com/amaurymartiny/shoot-i-smoke/commits/master), but yeah, I'm not 100% sure what's the issue really.

**Comment by amaurymartiny** [comment]
Hey @adi-mohan, any progress on this?

**Pull request closed without merging**
